name: publish
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build
      - name: upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: "Mod Publish"
    steps:
      - uses: actions/checkout@v6
      - name: download build artifact
        uses: actions/download-artifact@v8
        with:
          name: Artifacts
          path: build/libs
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 1KTbgBgQ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version-type: alpha
